export const ERROR_CONSTANT = {
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',

  JWT_SECRET_NOT_FOUND: 'JWT_SECRET_NOT_FOUND',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
};
